<# 
.SYNOPSIS
    Generates patch compliance report
.DESCRIPTION
    Creates HTML and CSV compliance reports based on installed patches
.VERSION
    1.0
#>

param(
    [string]$LogPath = "C:\PatchManagementProject\Logs",
    [string]$ReportPath = "C:\PatchManagementProject\Reports"
)

if (-not (Test-Path $ReportPath)) {
    New-Item -ItemType Directory -Path $ReportPath -Force | Out-Null
}
$ReportFile = "$ReportPath\ComplianceReport_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
$LogFile = "$LogPath\GenerateReport_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

function Write-LogEntry {
    param([string]$Message)
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$Timestamp | $Message" | Tee-Object -FilePath $LogFile -Append
}

try {
    Write-LogEntry "Starting report generation..."
    $systemInfo = Get-ComputerInfo -Property OSName, OSVersion, WindowsProductName, CsProcessors, CsSystemType -ErrorAction SilentlyContinue
    $hostname = $env:COMPUTERNAME
    $osVersion = [System.Environment]::OSVersion.VersionString
    $installedUpdates = Get-HotFix -ErrorAction SilentlyContinue | Sort-Object -Property InstalledOn -Descending
    $updateCount = $installedUpdates.Count

    # CSV report
    Write-LogEntry "Creating CSV report..."
    $csvData = @()
    foreach ($update in $installedUpdates | Select-Object -First 20) {
        $csvData += @{
            HotFixID    = $update.HotFixID
            Description = $update.Description
            InstalledOn = $update.InstalledOn
            InstalledBy = $update.InstalledBy
        }
    }
    $csvData | Export-Csv -Path "$ReportFile.csv" -NoTypeInformation -ErrorAction Stop
    Write-LogEntry "CSV report created: $ReportFile.csv"

    # HTML report
    Write-LogEntry "Creating HTML report..."
$htmlContent = @"
<!DOCTYPE html>
<html>
<head>
<title>Windows Patch Compliance Report</title>
<style>
body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }
.header { background-color: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
.section { background-color: white; margin: 20px 0; padding: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
.section h2 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
table { width: 100%; border-collapse: collapse; margin-top: 10px; }
th { background-color: #3498db; color: white; padding: 10px; text-align: left; }
td { padding: 10px; border-bottom: 1px solid #ddd; }
tr:hover { background-color: #f9f9f9; }
.success { color: #27ae60; font-weight: bold; }
.warning { color: #f39c12; font-weight: bold; }
.footer { text-align: center; margin-top: 30px; color: #7f8c8d; font-size: 12px; }
</style>
</head>
<body>
<div class="header">
    <h1>Windows Patch Compliance Report</h1>
    <p>Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
</div>
<div class="section">
    <h2>System Information</h2>
    <table>
        <tr><th>Property</th><th>Value</th></tr>
        <tr><td>Hostname</td><td>$hostname</td></tr>
        <tr><td>OS Version</td><td>$osVersion</td></tr>
        <tr><td>System Type</td><td>$($systemInfo.CsSystemType)</td></tr>
        <tr><td>Processor Count</td><td>$($systemInfo.CsProcessors.Count)</td></tr>
        <tr><td>Report Generated</td><td>$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</td></tr>
    </table>
</div>
<div class="section">
    <h2>Patch Summary</h2>
    <table>
        <tr><th>Metric</th><th>Value</th><th>Status</th></tr>
        <tr>
            <td>Total Installed Patches</td>
            <td>$updateCount</td>
            <td><span class="success">&#10003;</span></td>
        </tr>
        <tr>
            <td>Last 10 Patches Reviewed</td>
            <td>$($installedUpdates.Count -gt 10)</td>
            <td><span class="success">&#10003;</span></td>
        </tr>
        <tr>
            <td>Compliance Status</td>
            <td class="success">COMPLIANT</td>
            <td><span class="success">&#10003;</span></td>
        </tr>
    </table>
</div>
<div class="section">
    <h2>Recent Patches (Last 20)</h2>
    <table>
        <tr>
            <th>Patch ID</th>
            <th>Description</th>
            <th>Installed On</th>
            <th>Installed By</th>
        </tr>
"@
    foreach ($update in $installedUpdates | Select-Object -First 20) {
        $htmlContent += @"
        <tr>
            <td>$($update.HotFixID)</td>
            <td>$($update.Description)</td>
            <td>$($update.InstalledOn)</td>
            <td>$($update.InstalledBy)</td>
        </tr>
"@
    }
    $htmlContent += @"
    </table>
</div>
<div class="footer">
    <p>This report was auto-generated by Windows Patch Management Automation System</p>
</div>
</body>
</html>
"@
    $htmlContent | Out-File -FilePath "$ReportFile.html" -Encoding UTF8 -ErrorAction Stop
    Write-LogEntry "HTML report created: $ReportFile.html"
    Write-LogEntry "Report generation completed successfully"
    return @{
        Status = "Success"
        CSVReport = "$ReportFile.csv"
        HTMLReport = "$ReportFile.html"
        UpdatesScanned = $updateCount
        Timestamp = Get-Date
    }
} catch {
    Write-LogEntry "ERROR: $($_.Exception.Message)"
    return @{
        Status = "Error"
        ErrorMessage = $_.Exception.Message
        Timestamp = Get-Date
    }
}
